"""The Python mirror of the client's option order must match the real client.

`backend/answer_order.py` reimplements `orderedOptions` from
`src/components/ExerciseAnswerInput.tsx` in Python so curriculum gates can ask
"which button will the learner actually see first?". Two implementations of one
algorithm drift apart silently, so `fixtures/answer_order.json` - generated by
running the *actual* TypeScript function under Node - is asserted by both sides:

* here, for the Python mirror;
* in `src/components/ExerciseAnswerInput.test.tsx`, for the client function.

Either side changing without the other fails its own suite.
"""
from __future__ import annotations

import pytest

from backend.answer_order import (
    FIXTURE_PATH,
    displayed_options,
    key_shown_first,
    load_fixture,
    reorder_so_key_is_not_first,
)


def test_fixture_is_present():
    assert FIXTURE_PATH.exists(), (
        "fixtures/answer_order.json is missing; regenerate it by running the "
        "client's orderedOptions over the curriculum option lists in Node")
    assert load_fixture(), "the ordering fixture is empty"


@pytest.mark.parametrize("case", load_fixture(), ids=lambda case: case["id"])
def test_python_mirror_matches_the_client_order(case):
    assert displayed_options(case["id"], case["options"]) == case["displayed"], (
        f"display order for {case['id']!r} diverged from the client - "
        "backend/answer_order.py must be updated with ExerciseAnswerInput.tsx")


def test_short_lists_are_left_in_stored_order():
    assert displayed_options("anything", ["True", "False"]) == ["True", "False"]


def test_reorder_hides_the_key_from_the_first_slot():
    options = ["alpha", "beta", "gamma", "delta"]
    for answer in options:
        fixed = reorder_so_key_is_not_first("some-exercise-id", options, answer)
        assert answer in fixed
        assert len(fixed) == len(options)
        assert not key_shown_first("some-exercise-id", fixed, answer), (
            f"no arrangement of {options} hid {answer!r}")


def test_reorder_is_a_noop_when_already_hidden():
    options = displayed_options("calm-item", ["one", "two", "three"])
    answer = options[1]                      # not the first slot
    assert reorder_so_key_is_not_first("calm-item", options, answer) == options


def test_no_shipped_item_puts_its_answer_in_the_first_rendered_slot():
    from backend.curriculum_loader import load_all_curriculums

    offenders = []
    for curriculum in load_all_curriculums().values():
        for lesson in curriculum.lessons:
            items = [e for s in lesson.sublessons for e in s.exercises]
            items += list(lesson.mastery_exam or [])
            for exercise in items:
                answer = exercise.correct_answer
                options = [str(o) for o in (exercise.options or [])]
                if not isinstance(answer, str) or len(options) < 3:
                    continue
                if answer not in options:
                    continue
                if key_shown_first(exercise.id, options, answer):
                    offenders.append(exercise.id)
    assert not offenders, f"answers visible in slot one: {offenders}"
